# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa71195deea66700fb99ed5387969a9905c34a0ba8c3922a7fd693a45db7ba449f7b195dcd12ba0256d9cf3d25e31b5a613623c925aada4678579e2425f9ae82

test:
  secret_key_base: 905ab246ec397400de26c53b1c28b4eb8147041b6f5b12d9054684f3668e0277a1c2001629da8dbc8f3b2fc186266122de1330ec17528075e0b6f37550293eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
